# Server
server:
  port: 8084
# Spring
spring:
  # MVC
  mvc:
    servlet:
      path: /aula
# netflix-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.17:8761/eureka
