# Server
server:
  port: 8084
# Spring
spring:
  # MVC
  mvc:
    servlet:
      path: /aula
# netflix-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.2.140:8761/eureka
